made tests pass, showing ERROR or FAIL
To keep all tests that currently fail while
also producing a passing regression, the failing
test catch errors or just compare input to input.
Test names indicate, what's currently wrong:
 ERROR: $testname - [$comment] -> there was an Error in the compilation
 FAIL: $testname - [$comment] -> produced code was not-functional